base:
  project: music-recommendation-system
  random_state: 42
  target_col: TARGET

data_source:
  s3_source: data/processed/allsong_data.csv
  feature_source: data/processed/complete_feature.csv
  final_features: data/processed/final_features.csv

split_data:
  test_path: data/processed/test_playlist.csv

#add about model

model_dir: saved_models

#reports

#webapp_model_dir

#playlist URL
playlist_url: "https://open.spotify.com/playlist/6o14nYXSznAmdiJZT4MGfi?si=5267c9d23f53485b"
