base:
  project: music-recommendation-system
  random_state: 42
  target_col: TARGET

data_source:
  s3_source: data/processed/allsong_data.csv
  feature_source: data/processed/complete_feature.csv

split_data:
  test_path: data/processed/test_playlist.csv

#add about model

model_dir: saved_models

#reports

#webapp_model_dir